/* LyricSlide Pro - Core Logic v21.0 (Strict v19.5 Gen + v12 Transpose) */

const App = {
    version: "v21.0 (Deep Transparency + Transpose)",

    elements: {
        songTitle: document.getElementById('songTitle'),
        lyricsInput: document.getElementById('lyricsInput'),
        copyrightInfo: document.getElementById('copyrightInfo'),
        generateBtn: document.getElementById('generateBtn'),
        transFileInput: document.getElementById('transFileInput'),
        transposeBtn: document.getElementById('transposeBtn'),
        semitoneDisplay: document.getElementById('semitoneDisplay'),
        loadingOverlay: document.getElementById('loadingOverlay'),
        loadingText: document.getElementById('loadingText')
    },

    musical: {
        keys: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        flats: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']
    },

    originalSlides: [],   // Slide data for live preview
    selectedTemplateFile: null, 

    init() {
        const verEl = document.getElementById('appVersion');
        if (verEl) verEl.textContent = this.version;
        
        // Attach Actions
        if (this.elements.generateBtn) this.elements.generateBtn.onclick = () => this.generate();
        if (this.elements.transposeBtn) this.elements.transposeBtn.onclick = () => this.transpose();
        
        // Preview Trigger
        if (this.elements.transFileInput) {
            this.elements.transFileInput.onchange = (e) => this.loadForPreview(e.target.files[0]);
        }

        this.theme.init();
        this.loadDefaultTemplates(); 
        window.LyricApp = this;
    },

    theme: {
        defaults: { '--primary-color': '#334155', '--bg-start': '#f8fafc', '--bg-end': '#f8fafc', '--text-main': '#1e293b', '--card-accent': '#e2e8f0', '--preview-card-bg': '#ffffff', '--preview-chord-color': '#334155', '--preview-lyrics-color': '#1e293b' },
        init() {
            const saved = JSON.parse(localStorage.getItem('lyric_theme') || '{}');
            Object.keys(this.defaults).forEach(key => {
                const val = saved[key] || this.defaults[key];
                document.documentElement.style.setProperty(key, val);
            });
        }
    },

    // --- GENERATION ENGINE (STRICT v19.5 UNTOUCHED) ---
    async generate() {
        if (!this.selectedTemplateFile || !this.elements.lyricsInput.value) return alert('Select template and enter lyrics.');
        try {
            this.showLoading('Generating...');
            const zip = await JSZip.loadAsync(this.selectedTemplateFile);
            const presXml = await zip.file('ppt/presentation.xml').async('string');
            const presRelsXml = await zip.file('ppt/_rels/presentation.xml.rels').async('string');
            const slideRels = this.getSlideRels(presRelsXml);
            const templateRelPath = slideRels[this.getSlideIds(presXml)[0].rid];
            const templateXml = await zip.file(`ppt/${templateRelPath}`).async('string');
            const templateRelsXml = await zip.file(`ppt/slides/_rels/${templateRelPath.split('/').pop()}.rels`).async('string');
            
            const sections = ("\n" + this.elements.lyricsInput.value).split(/\r?\n(?=\s*\[(?!(?:Title|Copyright Info|Lyrics and Chords)\])[^\]\n]+\])/).filter(s => s.trim() !== '');
            const generated = [];
            const copyrightText = (this.elements.copyrightInfo.value ? this.elements.copyrightInfo.value + " | " : "") + "Generated by " + this.version;

            for (let i = 0; i < sections.length; i++) {
                let slideXml = this.lockInStyleAndReplace(templateXml, '[Title]', this.elements.songTitle.value);
                slideXml = this.lockInStyleAndReplace(slideXml, '[Copyright Info]', copyrightText);
                slideXml = this.lockInStyleAndReplace(slideXml, '[Lyrics and Chords]', sections[i].trim());

                const name = `song_gen_${i + 1}.xml`;
                zip.file(`ppt/slides/${name}`, slideXml);
                zip.file(`ppt/slides/_rels/${name}.rels`, templateRelsXml);
                generated.push({ id: 5000 + i, rid: `rIdGen${i + 1}`, name, path: `ppt/slides/${name}` });
            }

            this.syncPresentationRegistry(zip, presXml, presRelsXml, generated);
            saveAs(await zip.generateAsync({ type: 'blob' }), `${(this.elements.songTitle.value || 'Song').replace(/[^a-z0-9]/gi, '_')}.pptx`);
            this.hideLoading();
        } catch (e) { this.hideLoading(); alert("Error during generation."); }
    },

    lockInStyleAndReplace(xml, placeholder, replacement) {
        const createFuzzyRegex = (ph) => {
            const inner = ph.replace(/[\[\]]/g, '').trim();
            const fuzzy = inner.split('').map(c => 
                c === ' ' ? '\\s*' : `${this.escRegex(c)}(?:<[^>]+>)*`
            ).join('(?:<[^>]+>)*');
            return new RegExp('\\[' + '(?:<[^>]+>|\\s)*' + fuzzy + '(?:<[^>]+>|\\s)*' + '\\]', 'gi');
        };

        const phRegex = createFuzzyRegex(placeholder);
        const chordRegex = /\b([A-G][b#]?)(m|maj|dim|aug|sus|2|4|6|7|9|add|11|13)*(\/[A-G][b#]?)?\b/g;

        return xml.replace(/<(p:sp|p:graphicFrame)>([\s\S]*?)<\/\1>/g, (fullFrame, tagName, innerContent) => {
            phRegex.lastIndex = 0;
            if (phRegex.test(innerContent)) {
                
                const latinMatch = innerContent.match(/<a:latin typeface="([^"]+)"/);
                const templateFont = latinMatch ? latinMatch[1] : "Arial";
                const sizeMatch = innerContent.match(/sz="(\d+)"/);
                const templateSize = sizeMatch ? sizeMatch[1] : "2400"; 

                if (!/Lyrics/i.test(placeholder)) {
                    const rPrMatch = innerContent.match(/<a:rPr[^>]*>[\s\S]*?<\/a:rPr>/g);
                    let style = (rPrMatch ? rPrMatch[0] : '<a:rPr lang="en-US"/>');
                    const escapedText = (replacement || '').split(/\r?\n/).map(l => this.escXml(l)).join(`</a:t></a:r><a:br/><a:r>${style}<a:t xml:space="preserve">`);
                    return `<${tagName}>${innerContent.replace(phRegex, escapedText)}</${tagName}>`;
                }

                const lines = (replacement || '').split(/\r?\n/);
                let tableRowsXml = '';

                lines.forEach((line) => {
                    let trimmed = line.trim();
                    if (trimmed === '') {
                        tableRowsXml += this.createTableCellXml(" ", templateFont, templateSize, "ctr", 150000);
                        return;
                    }
                    const isTag = trimmed.startsWith('[') && trimmed.endsWith(']');
                    const hasChords = line.match(chordRegex);

                    if (isTag) {
                        tableRowsXml += this.createTableCellXml(trimmed, templateFont, Math.round(templateSize * 0.8), "ctr", 400000);
                    } else if (hasChords) {
                        const esc = this.escXml(line).replace(/ /g, '&#160;');
                        tableRowsXml += this.createTableCellXml(esc, "Courier New", templateSize, "ctr", 400000);
                    } else {
                        tableRowsXml += this.createTableCellXml(this.escXml(line), templateFont, templateSize, "ctr", 450000);
                    }
                });

                const rowsSplit = innerContent.split(/<a:tr[\s\S]*?<\/a:tr>/);
                let header = rowsSplit[0];
                header = header.replace(/<a:tableStyleId>[\s\S]*?<\/a:tableStyleId>/, '<a:tableStyleId>{5C22544A-7EE6-4342-B051-7303C2061113}</a:tableStyleId>');
                
                if (header.includes('</a:tblPr>')) {
                    header = header.replace('</a:tblPr>', '<a:wholeTbl><a:tcPr><a:noFill/></a:tcPr></a:wholeTbl></a:tblPr>');
                }

                const newInner = `${header}${tableRowsXml}${rowsSplit[rowsSplit.length - 1]}`;
                return `<${tagName}>${newInner}</${tagName}>`;
            }
            return fullFrame;
        });
    },

    createTableCellXml(text, font, size, align, height) {
        return `
        <a:tr h="${height}">
            <a:tc>
                <a:txBody>
                    <a:bodyPr vert="ctr" anchor="ctr" lIns="0" rIns="0" tIns="0" bIns="0"/>
                    <a:p>
                        <a:pPr algn="${align}"/>
                        <a:r>
                            <a:rPr sz="${size}" lang="en-US">
                                <a:latin typeface="${font}"/><a:cs typeface="${font}"/>
                            </a:rPr>
                            <a:t xml:space="preserve">${text}</a:t>
                        </a:r>
                    </a:p>
                </a:txBody>
                <a:tcPr>
                    <a:lnL w="0"><a:noFill/></a:lnL>
                    <a:lnR w="0"><a:noFill/></a:lnR>
                    <a:lnT w="0"><a:noFill/></a:lnT>
                    <a:lnB w="0"><a:noFill/></a:lnB>
                    <a:noFill/>
                </a:tcPr>
            </a:tc>
        </a:tr>`;
    },

    // --- TRANSPOSITION ENGINE (PORTED FROM v12) ---
    async transpose() {
        const file = this.elements.transFileInput.files[0];
        const semitones = parseInt(this.elements.semitoneDisplay.textContent) || 0;

        const getSz = id => { 
            const el = document.getElementById(id);
            if (!el) return null;
            const v = parseFloat(el.value); 
            return (!isNaN(v) && v > 0) ? Math.round(v * 100) : null; 
        };
        const getFont = id => document.getElementById(id)?.value?.trim();

        const titleFont = getFont('fontTitle');    const titleSize = getSz('fontSizeTitle');
        const lyricsFont = getFont('fontLyrics');   const lyricsSize = getSz('fontSizeLyrics');
        const copyFont = getFont('fontCopyright'); const copySize = getSz('fontSizeCopyright');

        const anyFontChange = titleFont || titleSize || lyricsFont || lyricsSize || copyFont || copySize;

        if (!file) return alert('Select a PPTX file.');
        if (semitones === 0 && !anyFontChange) return alert('No changes requested.');

        try {
            this.showLoading('Processing...');
            const zip = await JSZip.loadAsync(file);
            
            // 1. Process Slide Files
            const slideFiles = Object.keys(zip.files).filter(k => k.startsWith('ppt/slides/slide') && k.endsWith('.xml'));

            for (const path of slideFiles) {
                let content = await zip.file(path).async('string');
                if (semitones !== 0) {
                    content = content.replace(/<a:t>(.*?)<\/a:t>/g, (_, text) =>
                        `<a:t>${this.transposeLine(this.unescXml(text), semitones)}</a:t>`);
                }

                if (anyFontChange) {
                    content = content.replace(/<p:sp>([\s\S]*?)<\/p:sp>/g, (shapeMatch, shapeContent) => {
                        const isTitle = /<p:ph[^>]*type="(?:title|ctrTitle)"/.test(shapeContent);
                        const isFooter = /<p:ph[^>]*type="ftr"/.test(shapeContent);
                        const isSkipped = /<p:ph[^>]*type="(?:dt|sldNum)"/.test(shapeContent);
                        if (isSkipped) return shapeMatch;
                        const isCopyright = isFooter || /©|copyright|ccli/i.test(shapeContent.replace(/<[^>]+>/g, ''));

                        let targetFont, targetSize;
                        if (isTitle) { targetFont = titleFont; targetSize = titleSize; }
                        else if (isCopyright) { targetFont = copyFont; targetSize = copySize; }
                        else { targetFont = lyricsFont; targetSize = lyricsSize; }

                        if (!targetFont && !targetSize) return shapeMatch;
                        return `<p:sp>${this.applyFontToShapeXml(shapeContent, targetFont, targetSize)}</p:sp>`;
                    });
                }
                zip.file(path, content);
            }

            // 2. Process Notes
            if (semitones !== 0) {
                const notesFiles = Object.keys(zip.files).filter(k => k.startsWith('ppt/notesSlides/notesSlide') && k.endsWith('.xml'));
                for (const path of notesFiles) {
                    let notesContent = await zip.file(path).async('string');
                    notesContent = notesContent.replace(/<a:t>(.*?)<\/a:t>/g, (_, text) =>
                        `<a:t>${this.transposeLine(this.unescXml(text), semitones)}</a:t>`);
                    zip.file(path, notesContent);
                }
            }

            saveAs(await zip.generateAsync({ type: 'blob' }), file.name.replace('.pptx', `_modified.pptx`));
            this.hideLoading();
        } catch (err) { this.hideLoading(); alert("Error: " + err.message); }
    },

    transposeLine(text, semitones) {
        if (semitones === 0) return text;
        const lines = text.split('\n');
        const chordRegex = /\b([A-G][b#]?)(m|maj|dim|aug|sus|2|4|6|7|9|add|11|13)*(\/[A-G][b#]?)?\b/g;
        return lines.map(line => {
            const words = line.split(/\s+/).filter(w => w.length > 0);
            const chordCount = (line.match(chordRegex) || []).length;
            if (chordCount === 0 || chordCount < words.length * 0.4) return line;

            let result = line, offset = 0;
            const matches = [...line.matchAll(chordRegex)];
            for (const m of matches) {
                const original = m[0], pos = m.index + offset;
                const nc = this.shiftNote(m[1], semitones) + (m[2] || '') + (m[3] ? '/' + this.shiftNote(m[3].substring(1), semitones) : '');
                const diff = nc.length - original.length;
                result = result.substring(0, pos) + nc + result.substring(pos + original.length);
                if (diff > 0) {
                    let spaceMatch = result.substring(pos + nc.length).match(/^ +/);
                    if (spaceMatch && spaceMatch[0].length >= diff) result = result.substring(0, pos + nc.length) + result.substring(pos + nc.length + diff);
                    else offset += diff;
                } else if (diff < 0) {
                    result = result.substring(0, pos + nc.length) + " ".repeat(Math.abs(diff)) + result.substring(pos + nc.length);
                }
            }
            return result;
        }).join('\n');
    },

    shiftNote(note, semitones) {
        let list = note.includes('b') ? this.musical.flats : this.musical.keys;
        let idx = list.indexOf(note);
        if (idx === -1) { list = (list === this.musical.keys ? this.musical.flats : this.musical.keys); idx = list.indexOf(note); }
        if (idx === -1) return note;
        return (semitones >= 0 ? this.musical.keys : this.musical.flats)[(idx + semitones + 12) % 12];
    },

    applyFontToShapeXml(shapeXml, fontFamily, fontSizeHundredths) {
        shapeXml = shapeXml.replace(/<a:rPr([^>]*)\/>/g, (_, attrs) => {
            const newAttrs = this.applyFontSizeToAttrs(attrs, fontSizeHundredths);
            return `<a:rPr${newAttrs}>${this.buildFontTags(fontFamily)}</a:rPr>`;
        });
        shapeXml = shapeXml.replace(/<a:rPr([^>]*)>([\s\S]*?)<\/a:rPr>/g, (_, attrs, inner) => {
            const newAttrs = this.applyFontSizeToAttrs(attrs, fontSizeHundredths);
            if (fontFamily) inner = inner.replace(/<a:(latin|ea|cs)[^>]*\/>/g, '').replace(/<a:(latin|ea|cs)[^>]*>[\s\S]*?<\/a:\1>/g, '');
            return `<a:rPr${newAttrs}>${this.buildFontTags(fontFamily)}${inner}</a:rPr>`;
        });
        return shapeXml;
    },

    applyFontSizeToAttrs(attrs, sz) {
        if (!sz) return attrs;
        return /\bsz="[^"]+"/.test(attrs) ? attrs.replace(/\bsz="[^"]+"/, `sz="${sz}"`) : attrs + ` sz="${sz}"`;
    },

    buildFontTags(f) {
        if (!f) return '';
        const e = this.escXml(f);
        return `<a:latin typeface="${e}"/><a:ea typeface="${e}"/><a:cs typeface="${e}"/>`;
    },

    // --- PREVIEW ENGINE (PORTED FROM v12) ---
    async loadForPreview(file) {
        if (!file) return;
        try {
            this.showLoading('Loading preview...');
            const zip = await JSZip.loadAsync(file);
            const slideFiles = Object.keys(zip.files)
                .filter(k => k.startsWith('ppt/slides/slide') && k.endsWith('.xml'))
                .sort((a, b) => parseInt(a.match(/\d+/)[0]) - parseInt(b.match(/\d+/)[0]));

            this.originalSlides = [];
            for (const path of slideFiles) {
                const xml = await zip.file(path).async('string');
                const slideData = [];
                const spRegex = /<p:sp>([\s\S]*?)<\/p:sp>/g;
                let spMatch;
                while ((spMatch = spRegex.exec(xml)) !== null) {
                    const spContent = spMatch[1];
                    const pRegex = /<a:p>([\s\S]*?)<\/a:p>/g;
                    let pMatch;
                    while ((pMatch = pRegex.exec(spContent)) !== null) {
                        const pContent = pMatch[1];
                        const tagRegex = /<(a:t|a:br)[^>]*>(.*?)<\/\1>|<a:br\/>/g;
                        let pText = '', match;
                        while ((match = tagRegex.exec(pContent)) !== null) {
                            if (match[0].startsWith('<a:br')) pText += '\n';
                            else pText += this.unescXml(match[2] || '');
                        }
                        slideData.push({ text: pText, alignment: pContent.includes('algn="ctr"') ? 'center' : 'left' });
                    }
                }
                this.originalSlides.push(slideData);
            }
            this.updatePreview(0);
            this.hideLoading();
        } catch (err) { this.hideLoading(); }
    },

    updatePreview(semitones) {
        const container = document.getElementById('previewContainer');
        if (!container) return;
        container.innerHTML = '';
        this.originalSlides.forEach((slideData, idx) => {
            const card = document.createElement('div');
            card.className = 'preview-card';
            const content = document.createElement('div');
            content.className = 'slide-content';
            slideData.forEach(p => {
                if (p.text.trim()) {
                    const l = document.createElement('div');
                    l.style.textAlign = p.alignment;
                    l.innerHTML = this.transposeLine(this.escXml(p.text), semitones).replace(/\b([A-G][b#]?)(m|maj|dim|aug|sus|2|4|6|7|9|add|11|13)*(\/[A-G][b#]?)?\b/g, '<span class="chord">$&</span>');
                    content.appendChild(l);
                }
            });
            card.innerHTML = `<div class="text-[10px] text-slate-400 mb-2">Slide ${idx+1}</div>`;
            card.appendChild(content);
            container.appendChild(card);
        });
    },

    // --- TEMPLATE LOAD (v19.5 UNTOUCHED) ---
    async loadDefaultTemplates() {
        const gallery = document.getElementById('templateGallery');
        try {
            const res = await fetch('./templates.json');
            const names = await res.json();
            document.getElementById('dirName').textContent = `${names.length} templates available`;
            gallery.innerHTML = '';
            const grid = document.createElement('div');
            grid.className = 'template-grid';
            names.forEach(name => {
                const card = document.createElement('div');
                card.className = 'template-card';
                card.innerHTML = `<img class="template-thumb" src="${name.replace('.pptx','.png')}" onerror="this.src='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 fill=%22%23eee%22/><text x=%2250%%22 y=%2250%%22 text-anchor=%22middle%22 dy=%22.3em%22 font-family=%22sans-serif%22 fill=%22%23999%22>PPTX</text></svg>'"><div class="template-card-name">${name.replace('.pptx','')}</div>`;
                card.onclick = async () => {
                    const r = await fetch(`./${encodeURIComponent(name)}`);
                    const blob = await r.blob();
                    this.selectedTemplateFile = new File([blob], name, { type: blob.type });
                    document.querySelectorAll('.template-card').forEach(c => c.classList.remove('selected'));
                    card.classList.add('selected');
                    document.getElementById('selectedTemplateInfo').classList.remove('hidden');
                    document.getElementById('selectedTemplateName').textContent = name;
                };
                grid.appendChild(card);
            });
            gallery.appendChild(grid);
        } catch (e) { gallery.innerHTML = 'Library load failed.'; }
    },

    // --- XML HELPERS (v19.5) ---
    showLoading(t) { this.elements.loadingText.textContent = t; this.elements.loadingOverlay.style.display = 'flex'; },
    hideLoading() { this.elements.loadingOverlay.style.display = 'none'; },
    unescXml(s) { return s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&apos;/g, "'"); },
    escXml(s) { return (s||'').replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c])); },
    escRegex(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); },
    getSlideIds(xml) { let ids = [], m, r = /<p:sldId[^>]+id="([^"]+)"[^>]+r:id="([^"]+)"/g; while (m = r.exec(xml)) ids.push({id: m[1], rid: m[2]}); return ids; },
    getSlideRels(xml) { let rels = {}, m, r = /<Relationship[^>]+Id="([^"]+)"[^>]+Type="[^"]+slide"[^>]+Target="([^"]+)"/g; while (m = r.exec(xml)) rels[m[1]] = m[2]; return rels; },
    syncPresentationRegistry(zip, pres, rels, gen) {
        const list = '<p:sldIdLst>' + gen.map(s => `<p:sldId id="${s.id}" r:id="${s.rid}"/>`).join('') + '</p:sldIdLst>';
        zip.file('ppt/presentation.xml', pres.replace(/<p:sldIdLst>[\s\S]*?<\/p:sldIdLst>/, list));
        let doc = new DOMParser().parseFromString(rels, 'application/xml');
        let rs = doc.getElementsByTagName('Relationship');
        for (let j = rs.length - 1; j >= 0; j--) if (rs[j].getAttribute('Type').endsWith('slide')) rs[j].parentNode.removeChild(rs[j]);
        gen.forEach(s => { let el = doc.createElement('Relationship'); el.setAttribute('Id', s.rid); el.setAttribute('Type', 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide'); el.setAttribute('Target', `slides/${s.name}`); doc.documentElement.appendChild(el); });
        zip.file('ppt/_rels/presentation.xml.rels', new XMLSerializer().serializeToString(doc));
        const head = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="pptx" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation"/><Default Extension="jpeg" ContentType="image/jpeg"/><Default Extension="png" ContentType="image/png"/>';
        let entries = gen.map(s => `<Override PartName="/${s.path}" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('');
        zip.file('[Content_Types].xml', (head + entries + '</Types>').replace('><Override', '><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>'));
    }
};

function changeSemitones(delta) {
    const d = document.getElementById('semitoneDisplay');
    let n = Math.max(-11, Math.min(11, (parseInt(d.textContent) || 0) + delta));
    d.textContent = (n > 0 ? '+' : '') + n;
    if (App.originalSlides.length > 0) App.updatePreview(n);
}

App.init();